# Generated by Django 5.0 on 2025-10-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el registro ha sido eliminado (soft delete).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(help_text='Nombre del distribuidor.', max_length=200)),
                ('apellidos', models.CharField(help_text='Apellido del distribuidor.', max_length=200)),
                ('dpi', models.CharField(help_text='Número de DPI del distribuidor.', max_length=20)),
                ('correo', models.EmailField(help_text='Dirección de correo electrónico del distribuidor.', max_length=254)),
                ('telefono', models.CharField(help_text='Número de teléfono del distribuidor.', max_length=20)),
                ('departamento', models.CharField(help_text='Departamento donde se encuentra el distribuidor.', max_length=100)),
                ('municipio', models.CharField(help_text='Municipio donde se encuentra el distribuidor.', max_length=100)),
                ('direccion', models.TextField(help_text='Dirección física del distribuidor.')),
                ('negocio_nombre', models.CharField(help_text='Nombre del negocio del distribuidor.', max_length=200)),
                ('nit', models.CharField(help_text='NIT del distribuidor.', max_length=20, unique=True)),
                ('telefono_negocio', models.CharField(blank=True, help_text='Número de teléfono del negocio del distribuidor.', max_length=20, null=True)),
                ('equipamiento', models.TextField(blank=True, help_text='Equipo de cómputo (computadoras, laptops, tablets, etc).', null=True)),
                ('sucursales', models.TextField(blank=True, help_text='Número de sucursales del distribuidor.', null=True)),
                ('antiguedad', models.CharField(help_text='Antigüedad del distribuidor en años.', max_length=50)),
                ('productos_distribuidos', models.CharField(help_text='Los productos que distribuye el distribuidor.', max_length=100)),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', help_text='Tipo de persona (natural o jurídica).', max_length=10)),
                ('cuenta_bancaria', models.CharField(help_text='Nombre de la cuenta bancaria del distribuidor.', max_length=100)),
                ('numero_cuenta', models.CharField(help_text='Número de cuenta del distribuidor.', max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('ahorro', 'Cuenta de Ahorro'), ('corriente', 'Cuenta Corriente'), ('monetaria', 'Cuenta Monetaria')], default='monetaria', help_text='Tipo de cuenta bancaria del distribuidor.', max_length=20)),
                ('banco', models.CharField(help_text='Banco asociado a la cuenta del distribuidor.', max_length=100)),
                ('estado', models.TextField(default='pendiente', help_text='Indica el estado del distribuidor en el sistema.', max_length=50)),
            ],
            options={
                'verbose_name': 'Distribuidor',
                'verbose_name_plural': 'Distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el registro ha sido eliminado (soft delete).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(help_text="Tipo de documento (ej. 'Contrato', 'Identificación').", max_length=100)),
                ('archivo', models.FileField(help_text='Archivo del documento.', upload_to='distribuidor/documentos/')),
                ('distribuidor', models.ForeignKey(help_text='Distribuidor asociado al documento.', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.distributor')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el registro ha sido eliminado (soft delete).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre de la sucursal o ubicación.', max_length=200)),
                ('departamento', models.CharField(help_text='Departamento donde se encuentra la ubicación.', max_length=255)),
                ('municipio', models.CharField(help_text='Municipio donde se encuentra la ubicación.', max_length=100)),
                ('direccion', models.CharField(help_text='Dirección física de la ubicación.', max_length=255)),
                ('telefono', models.CharField(help_text='Número de teléfono de la ubicación.', max_length=20)),
                ('distribuidor', models.ForeignKey(help_text='Distribuidor asociado a la ubicación.', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.distributor')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el registro ha sido eliminado (soft delete).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(help_text='Nombre de la referencia.', max_length=200)),
                ('telefono', models.CharField(help_text='Número de teléfono de la referencia.', max_length=20)),
                ('relacion', models.CharField(help_text='Relación de la referencia con el distribuidor.', max_length=100)),
                ('distribuidor', models.ForeignKey(help_text='Distribuidor asociado a la referencia.', on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='api.distributor')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
    ]
