# Generated by Django 5.0 on 2025-10-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el registro ha sido eliminado (soft delete).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(help_text='Descripción de la acción realizada', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales de la acción', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que ejecutó la acción', on_delete=django.db.models.deletion.PROTECT, related_name='auditlogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditlog',
                'verbose_name_plural': 'Auditlogs',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['usuario', 'created'], name='api_auditlo_usuario_665f9b_idx'), models.Index(fields=['created'], name='api_auditlo_created_d80f5f_idx')],
            },
        ),
    ]
