# Generated by Django 5.0 on 2025-10-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el registro ha sido eliminado (soft delete).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(help_text='Nombre del cliente.', max_length=120)),
                ('apellidos', models.CharField(blank=True, help_text='Apellidos del cliente.', max_length=120, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del cliente.', null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del cliente.', null=True)),
                ('dpi', models.CharField(help_text='Documento Personal de Identificación (DPI).', max_length=13, unique=True)),
                ('nit', models.CharField(blank=True, help_text='Número de Identificación Tributaria (NIT). Único si se proporciona.', max_length=13, null=True)),
                ('email', models.EmailField(help_text='Correo electrónico del cliente.', max_length=254, unique=True)),
                ('telefono', models.CharField(help_text='Número de teléfono del cliente.', max_length=15)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='can_create_clients',
            field=models.BooleanField(default=False, help_text='Permite al rol crear nuevos clientes.'),
        ),
        migrations.AddField(
            model_name='rol',
            name='can_delete_clients',
            field=models.BooleanField(default=False, help_text='Permite al rol eliminar clientes.'),
        ),
        migrations.AddField(
            model_name='rol',
            name='can_update_clients',
            field=models.BooleanField(default=False, help_text='Permite al rol editar clientes existentes.'),
        ),
    ]
