# Generated by Django 5.0 on 2025-12-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributordocument',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Falló'), ('INCORRECT', 'Incorrecto')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Falló'), ('INCORRECT', 'Incorrecto')], default='PENDING', max_length=20),
        ),
    ]
