# Generated by Django 5.0 on 2025-11-13 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationrequest",
            name="asignado_a",
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="assignment_key",
            field=models.ForeignKey(
                blank=True,
                help_text="El colaborador revisor que tiene asignada esta solicitud.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_asignadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="observaciones",
            field=models.TextField(
                blank=True,
                help_text="Observaciones o correcciones solicitadas por el revisor.",
            ),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="estado",
            field=models.CharField(
                choices=[
                    ("procesando_documentos", "Procesando Documentos (OCR)"),
                    ("pendiente_asignacion", "Pendiente de Asignación"),
                    ("asignada", "Asignada"),
                    ("en_revision", "En Revisión"),
                    ("pendiente_correcciones", "Pendiente de Correcciones"),
                    (
                        "pendiente_aprobacion",
                        "Pendiente de Aprobación (Enviado a autorizar)",
                    ),
                    ("aprobado", "Aprobado (Distribuidor creado)"),
                    ("rechazado", "Rechazado"),
                    ("error_ocr", "Error en OCR"),
                ],
                db_index=True,
                default="procesando_documentos",
                help_text="Estado de la solicitud en el flujo de aprobación.",
                max_length=50,
            ),
        ),
    ]
