# Generated by Django 5.0 on 2025-10-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_distributor_document_location_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='can_delete_distributors',
            field=models.BooleanField(default=False, help_text='Permite al rol eliminar distribuidores.'),
        ),
        migrations.AddField(
            model_name='rol',
            name='can_update_distributors',
            field=models.BooleanField(default=False, help_text='Permite al rol actualizar distribuidores.'),
        ),
    ]
