# Generated by Django 5.0 on 2025-11-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rol_can_authorize_requests_rol_can_be_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorrequest',
            name='ocr_match_score',
            field=models.IntegerField(default=0, help_text='Puntaje de coincidencia (0-100) calculado entre datos OCR y manuales.'),
        ),
    ]
