# Generated by Django 5.0 on 2025-10-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='can_view_auditlogs',
            field=models.BooleanField(default=False, help_text='Permite al rol ver los registros de auditoría.'),
        ),
    ]
