# Generated by Django 5.0 on 2025-10-28 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rol_can_delete_distributors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignmentdistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el registro ha sido eliminado (soft delete).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('distribuidor', models.ForeignKey(help_text='Distribuidor asignado al usuario.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.distributor')),
                ('usuario', models.ForeignKey(help_text='Usuario al que se le asigna el distribuidor.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.CreateModel(
            name='Revisiondistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el registro ha sido eliminado (soft delete).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios sobre la revisión del distribuidor.')),
                ('aprobado', models.BooleanField(default=False, help_text='Indica si el distribuidor fue aprobado en la revisión.')),
                ('distribuidor', models.ForeignKey(help_text='Distribuidor asociado a la revisión.', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.distributor')),
            ],
            options={
                'verbose_name': 'Revisión Distributor',
                'verbose_name_plural': 'Revisiones Distributors',
            },
        ),
        migrations.CreateModel(
            name='Trackingdistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo lógicamente.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el registro ha sido eliminado (soft delete).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(help_text="Estado actual del distribuidor (ej. 'Activo', 'Inactivo').", max_length=50)),
                ('observacion', models.TextField(blank=True, help_text='Observaciones adicionales sobre el distribuidor.')),
                ('distribuidor', models.ForeignKey(help_text='Distribuidor asociado al seguimiento.', on_delete=django.db.models.deletion.CASCADE, related_name='trackingdistributors', to='api.distributor')),
            ],
            options={
                'verbose_name': 'Tracking Distributor',
                'verbose_name_plural': 'Tracking Distributors',
            },
        ),
    ]
