# Generated by Django 5.0 on 2025-11-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_distributorrequest_ocr_match_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorrequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Asignación'), ('asignada', 'Asignada a Colaborador'), ('en_revision', 'En Revisión (Colaborador)'), ('correcciones_solicitadas', 'Correcciones Solicitadas'), ('en_reenvio', 'En Reenvío (Aplicante corrigió)'), ('en_validacion_final', 'En Validación Final'), ('enviado_autorizacion', 'Enviado a Autorización Final'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('draft', 'Borrador')], db_index=True, default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesttracking',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente de Asignación'), ('asignada', 'Asignada a Colaborador'), ('en_revision', 'En Revisión (Colaborador)'), ('correcciones_solicitadas', 'Correcciones Solicitadas'), ('en_reenvio', 'En Reenvío (Aplicante corrigió)'), ('en_validacion_final', 'En Validación Final'), ('enviado_autorizacion', 'Enviado a Autorización Final'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('draft', 'Borrador')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requesttracking',
            name='estado_nuevo',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Asignación'), ('asignada', 'Asignada a Colaborador'), ('en_revision', 'En Revisión (Colaborador)'), ('correcciones_solicitadas', 'Correcciones Solicitadas'), ('en_reenvio', 'En Reenvío (Aplicante corrigió)'), ('en_validacion_final', 'En Validación Final'), ('enviado_autorizacion', 'Enviado a Autorización Final'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('draft', 'Borrador')], max_length=50),
        ),
    ]
