# Generated by Django 5.0 on 2025-10-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_rol_can_create_clients_rol_can_delete_clients_and_more'),
        ('api', '0004_assignmentdistributor_revisiondistributor_and_more'),
    ]

    operations = [
    ]
