# Generated by Django 5.0 on 2025-12-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_distributordocument_ocr_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributordocument',
            name='document_type',
            field=models.CharField(choices=[('DPI_FRONT', 'DPI (Frente)'), ('DPI_FRONT_REPRESENTANTE', 'DPI Frente (Representante Legal)'), ('DPI_BACK', 'DPI (Reverso)'), ('DPI_BACK_REPRESENTANTE', 'DPI Reverso (Representante Legal)'), ('RTU', 'RTU Digital'), ('PATENTE', 'Patente de Comercio'), ('OTHER', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='document_type',
            field=models.CharField(choices=[('DPI_FRONT', 'DPI (Frente)'), ('DPI_FRONT_REPRESENTANTE', 'DPI Frente (Representante Legal)'), ('DPI_BACK', 'DPI (Reverso)'), ('DPI_BACK_REPRESENTANTE', 'DPI Reverso (Representante Legal)'), ('RTU', 'RTU Digital'), ('PATENTE', 'Patente de Comercio'), ('OTHER', 'Otro')], max_length=30),
        ),
    ]
