# Generated by Django 5.0 on 2025-10-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20251028_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisiondistributor',
            name='campo',
            field=models.CharField(blank=True, help_text='Campo específico dentro de la sección que está siendo revisado.', max_length=100),
        ),
        migrations.AddField(
            model_name='revisiondistributor',
            name='seccion',
            field=models.CharField(blank=True, help_text='Sección del distribuidor que está siendo revisada.', max_length=100),
        ),
    ]
