# Generated by Django 5.0 on 2025-10-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_revisiondistributor_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='estado',
            field=models.CharField(blank=True, default=None, help_text="Estado de verificación: NULL=no verificado, 'verificado'=aprobado, 'rechazado'=desestimado.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='estado',
            field=models.CharField(blank=True, default=None, help_text="Estado de verificación: NULL=no verificado, 'verificado'=aprobado, 'rechazado'=desestimado.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='estado',
            field=models.CharField(blank=True, default=None, help_text="Estado de verificación: NULL=no verificado, 'verificado'=aprobado, 'rechazado'=desestimado.", max_length=50, null=True),
        ),
    ]
