# Generated by Django 5.0 on 2025-11-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_document_estado_location_estado_reference_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='negocio_nombre',
            field=models.CharField(blank=True, help_text='Nombre del negocio del distribuidor.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='nit',
            field=models.CharField(blank=True, help_text='NIT del distribuidor.', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='distributor',
            constraint=models.UniqueConstraint(condition=models.Q(('nit__isnull', False)), fields=('nit',), name='unique_nit_not_null'),
        ),
    ]
