# Generated by Django 5.0 on 2025-11-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rol_can_view_auditlogs'),
        ('api', '0007_document_estado_location_estado_reference_estado'),
    ]

    operations = [
    ]
