# Generated by Django 5.0 on 2025-11-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_distributor_negocio_nombre_and_more'),
        ('api', '0008_merge_20251103_1316'),
    ]

    operations = [
    ]
